import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Link,NavLink,Navigate,Route,Routes,useLocation,useNavigate,useParams}from'react-router-dom';
import{trip,statusLabel,type DayId}from'./data/trip';
import{memberName}from'./data/members';
import{events,dayEvents,type Event}from'./data/events';
import{spots,spotById,type Spot}from'./data/spots';
import{reservationById,reservationLabel}from'./data/reservations';
import{packingItems}from'./data/packing';
import{nextEvent,tripPhase}from'./domain/status';
import './style.css';
const iconPaths:Record<string,string>={home:'M3 10 12 3l9 7v10H3z M9 20v-6h6v6',route:'M5 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm14 10a3 3 0 1 0 0 6 3 3 0 0 0 0-6z M7 7h8a4 4 0 0 1 0 8H9',members:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm8 0a3 3 0 1 0 0-6 M2 21v-3a6 6 0 0 1 12 0v3z M16 15a5 5 0 0 1 6 5v1h-6',base:'M3 21V7l9-4 9 4v14z M9 21v-7h6v7 M7 10h2 M15 10h2',bag:'M4 8h16l-1 13H5z M9 8V6a3 3 0 0 1 6 0v2',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 11v5 M12 8h.01',arrow:'M4 12h15 M13 6l6 6-6 6',pin:'M12 21s7-6.2 7-11a7 7 0 0 0-14 0c0 4.8 7 11 7 11z M12 8a2 2 0 1 0 0 4 2 2 0 0 0 0-4z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 7v5l3 2',check:'M4 12l5 5L20 6'};
function Icon({name,size=20}:{name:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[name]||iconPaths.info}/></svg>}
function External({url,label,kind='link'}:{url:string|null|undefined;label:string;kind?:string}){if(!url)return null;return <a className="outline-button" href={url} target="_blank" rel="noopener noreferrer" aria-label={`${label}（外部サイト、新しいタブで開く）`}><Icon name={kind==='map'?'pin':'arrow'} size={17}/>{label}<span aria-hidden="true">↗</span></a>}
function MapLink({spot}:{spot:Spot|undefined}){return spot?.mapsUrl?<External url={spot.mapsUrl} label="地図を開く" kind="map"/>:<span className="muted-inline">場所は調整中</span>}
function Header(){return <header className="topbar"><Link to="/" className="brand"><span className="brand-mark">◈</span><span>ITSUMEN <small>YUZAWA 2026</small></span></Link><span className="topbar-date">10.11 SUN — 10.12 MON</span></header>}
function Nav(){const phase=tripPhase(new Date());return <nav className="bottom-nav" aria-label="メインナビゲーション"><NavLink to="/" end><Icon name="home"/><span>HOME</span></NavLink><NavLink to={`/itinerary/${phase.day}`} className={({isActive})=>isActive||location.pathname.startsWith('/itinerary')?'active':''}><Icon name="route"/><span>旅程</span></NavLink><NavLink to="/members"><Icon name="members"/><span>仲間</span></NavLink><NavLink to="/base"><Icon name="base"/><span>拠点</span></NavLink></nav>}
function ScrollManager(){const location=useLocation();useEffect(()=>{if(location.hash){const id=decodeURIComponent(location.hash.slice(1));setTimeout(()=>document.getElementById(id)?.scrollIntoView({block:'start'}),50)}else{window.scrollTo(0,0);document.getElementById('page-title')?.focus()}},[location.pathname,location.hash]);return null}
function Layout(){const route=useLocation();return <><ScrollManager/><Header/><main id="main" className={`page-container${route.pathname==='/members'?' members-screen':''}`}><Routes><Route path="/" element={<Home/>}/><Route path="/itinerary" element={<ItineraryRedirect/>}/><Route path="/itinerary/:day" element={<Itinerary/>}/><Route path="/members" element={<Members/>}/><Route path="/base" element={<Base/>}/><Route path="/info" element={<Info/>}/><Route path="/packing" element={<Packing/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Nav/></>}
function ItineraryRedirect(){return <Navigate replace to={`/itinerary/${tripPhase(new Date()).day}`}/>}
function WoodTitle({eyebrow,children}:{eyebrow:string;children:React.ReactNode}){return <div className="wood-title"><span>{eyebrow}</span><h1 id="page-title" tabIndex={-1}>{children}</h1></div>}
function DaySwitcher({active}:{active?:DayId}){return <div className="day-switcher" aria-label="日付を選択"><Link aria-current={active==='day1'?'page':undefined} to="/itinerary/day1"><span>DAY 1</span><small>10月11日 日</small></Link><Link aria-current={active==='day2'?'page':undefined} to="/itinerary/day2"><span>DAY 2</span><small>10月12日 月</small></Link></div>}
type PosterHotspot={label:string;to?:string;left:number;top:number;width:number;height:number;kind:'sign'|'character'|'scene';clip:string};
const signCut='polygon(6% 7%,89% 3%,98% 19%,100% 77%,92% 96%,8% 100%,0 79%,1% 21%)';
const swordCut='polygon(28% 1%,51% 0,60% 11%,69% 28%,82% 7%,91% 13%,92% 56%,100% 68%,96% 93%,75% 100%,18% 99%,0 84%,8% 58%,16% 44%,16% 18%)';
const golemCut='polygon(33% 2%,51% 0,70% 9%,77% 25%,79% 40%,94% 48%,100% 65%,88% 73%,78% 69%,82% 91%,71% 100%,26% 100%,16% 91%,20% 72%,4% 71%,0 54%,18% 42%,19% 22%)';
const buildingCut='polygon(7% 26%,33% 9%,55% 0,90% 18%,99% 32%,95% 95%,4% 100%,0 40%)';
const homeHotspots:PosterHotspot[]=[
 {label:'ホテルをタップして拠点情報へ',to:'/base',left:43,top:35,width:34,height:19,kind:'scene',clip:buildingCut},
 {label:'パノラマパークの看板を押して予定へ',to:'/itinerary/day1#d1-park',left:0,top:39,width:21,height:8,kind:'sign',clip:signCut},
 {label:'温泉の看板を押して自由行動の予定へ',to:'/itinerary/day1#d1-free',left:82,top:42,width:18,height:8,kind:'sign',clip:signCut},
 {label:'左端の剣士をタップして仲間図鑑へ',to:'/members',left:0,top:54,width:22,height:24,kind:'character',clip:swordCut},
 {label:'左から2人目の剣士をタップして仲間図鑑へ',to:'/members',left:22,top:58,width:18,height:20,kind:'character',clip:swordCut},
 {label:'中央の剣士をタップして仲間図鑑へ',to:'/members',left:40,top:59,width:19,height:20,kind:'character',clip:swordCut},
 {label:'右から2人目の剣士をタップして仲間図鑑へ',to:'/members',left:59,top:56,width:20,height:22,kind:'character',clip:swordCut},
 {label:'右端の剣士をタップして仲間図鑑へ',to:'/members',left:79,top:54,width:21,height:24,kind:'character',clip:swordCut},
 {label:'へぎそばの看板を押して予定へ',to:'/itinerary/day1#d1-lunch',left:0,top:80,width:22,height:9,kind:'sign',clip:signCut},
 {label:'トレッキングの看板を押して予定へ',to:'/itinerary/day1#d1-park',left:22,top:80,width:20,height:9,kind:'sign',clip:signCut},
 {label:'釣りとBBQの看板を押して予定へ',to:'/itinerary/day2#d2-fishing',left:42,top:80,width:19,height:9,kind:'sign',clip:signCut},
 {label:'テニスの看板を押して自由行動の予定へ',to:'/itinerary/day1#d1-free',left:61,top:80,width:20,height:9,kind:'sign',clip:signCut},
 {label:'乾杯の看板を押して夜ご飯の予定へ',to:'/itinerary/day1#d1-dinner',left:81,top:80,width:19,height:9,kind:'sign',clip:signCut},
];
const memberHotspots:PosterHotspot[]=[
 {label:'戻るボタンを押してHOMEへ',to:'/',left:2,top:17,width:22,height:8,kind:'sign',clip:signCut},
 {label:'ホームボタンを押してHOMEへ',to:'/',left:78,top:17,width:22,height:8,kind:'sign',clip:signCut},
 {label:'えいじをタップ',left:4,top:35,width:27,height:23,kind:'character',clip:swordCut},
 {label:'ゆうたをタップ',left:70,top:35,width:27,height:23,kind:'character',clip:swordCut},
 {label:'たかひろをタップ',left:31,top:32,width:38,height:34,kind:'character',clip:golemCut},
 {label:'ゆうへいをタップ',left:3,top:64,width:29,height:24,kind:'character',clip:swordCut},
 {label:'りょうをタップ',left:36,top:70,width:29,height:24,kind:'character',clip:swordCut},
 {label:'よしひとをタップ',left:69,top:64,width:29,height:24,kind:'character',clip:swordCut},
];
function ImagePoster({kind}:{kind:'home'|'members'}){
 const hotspots=kind==='home'?homeHotspots:memberHotspots;
 const [pressed,setPressed]=useState<number|null>(null);
 const navigate=useNavigate();
 const pressTimer=React.useRef<number|null>(null);
 useEffect(()=>()=>{if(pressTimer.current!==null)window.clearTimeout(pressTimer.current)},[]);
 function handlePress(event:React.MouseEvent<HTMLElement>,spot:PosterHotspot,index:number){
  if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||event.defaultPrevented)return;
  event.preventDefault();
  if(pressTimer.current!==null)return;
  setPressed(index);
  const duration=window.matchMedia('(prefers-reduced-motion: reduce)').matches?100:290;
  pressTimer.current=window.setTimeout(()=>{pressTimer.current=null;setPressed(null);if(spot.to)navigate(spot.to)},duration);
 }
 return <div className={`image-poster image-poster-${kind}`}><img src={`/assets/${kind}-poster.webp`} width="941" height="1672" alt="" loading={kind==='home'?'eager':'lazy'} fetchPriority={kind==='home'?'high':'auto'}/>{hotspots.map((spot,i)=>{
  const crop={backgroundImage:`url(/assets/${kind}-poster.webp)`,backgroundSize:`${10000/spot.width}% ${10000/spot.height}%`,backgroundPosition:`${spot.left/(100-spot.width)*100}% ${spot.top/(100-spot.height)*100}%`};
  const className=`poster-hotspot poster-hotspot-${spot.kind}${pressed===i?' is-pressed':''}`;
  const style={left:`${spot.left}%`,top:`${spot.top}%`,width:`${spot.width}%`,height:`${spot.height}%`,clipPath:spot.clip};
  const art=<span className="poster-hotspot-art" style={crop} aria-hidden="true"/>;
  return spot.to?<Link key={i} className={className} to={spot.to} aria-label={spot.label} onClick={event=>handlePress(event,spot,i)} style={style}>{art}</Link>:<button key={i} type="button" className={className} aria-label={spot.label} onClick={event=>handlePress(event,spot,i)} style={style}>{art}</button>;
 })}</div>
}
function Home(){const [now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);const onVisible=()=>setNow(new Date());document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',onVisible)}},[]);const phase=tripPhase(now),next=nextEvent(now),spot=next.event?spotById(next.event.spotId):undefined;return <><h1 id="page-title" className="sr-only" tabIndex={-1}>いつメン越後湯沢旅行 2026</h1><ImagePoster kind="home"/><p className="poster-note">看板や仲間をタップして詳細へ<span>2026年10月11日〜12日・越後湯沢／たかひろはDAY1 18:30集合・場所は調整中</span></p><section className="status-strip"><span className="status-dot"/><strong>{phase.label}</strong><span>日本時間で表示</span></section><section className="home-next" aria-labelledby="next-heading"><div className="section-heading"><div><span className="eyebrow">UP NEXT</span><h2 id="next-heading">{next.heading}</h2></div><Icon name="clock" size={28}/></div>{next.event?<div className="next-body"><div className="next-time">{next.event.timeLabel.replace('（仮）','')}</div><div><h3>{next.event.title}</h3><p>{next.event.summary}</p></div><div className="status-badge" data-status={next.event.status}>{statusLabel[next.event.status]}</div></div>:<p className="next-empty">{next.note}</p>}{next.event&&<p className="next-note">{next.note}</p>}<div className="button-row"><Link className="solid-button" to={next.event?`/itinerary/${next.day}#${next.event.id}`:`/itinerary/${next.day}`}>旅程を見る <Icon name="arrow" size={18}/></Link>{spot?.mapsUrl&&<MapLink spot={spot}/>}</div></section><div className="section-heading day-heading"><div><span className="eyebrow">THE JOURNEY</span><h2>2日間の旅程</h2></div><span className="leaf-accent">✿</span></div><DaySwitcher/><div className="quick-grid"><Link to="/info" className="quick-card"><span className="quick-icon"><Icon name="info" size={24}/></span><span><strong>旅行情報</strong><small>集合・食事・予約</small></span><Icon name="arrow" size={18}/></Link><Link to="/packing" className="quick-card"><span className="quick-icon"><Icon name="bag" size={24}/></span><span><strong>持ち物</strong><small>準備をチェック</small></span><Icon name="arrow" size={18}/></Link></div><div className="home-lower"><Link to="/members" className="feature-link"><strong>6人の仲間図鑑</strong><span>みんなの役割を見る →</span></Link><Link to="/base" className="feature-link"><strong>旅の拠点</strong><span>NASPAニューオータニ →</span></Link></div><p className="update-note">最終更新：{trip.updatedAt}　{trip.updateSummary} <button onClick={()=>location.reload()}>再読み込み</button></p></>}
function EventCard({event,index}:{event:Event;index:number}){const route=useLocation();const [open,setOpen]=useState(()=>route.hash===`#${event.id}`);const spot=spotById(event.spotId),reservation=reservationById(event.reservationId);useEffect(()=>{if(route.hash===`#${event.id}`)setOpen(true)},[event.id,route.hash]);return <li id={event.id} className="route-item"><span className="route-number" aria-hidden="true">{index+1}</span><article className={`event-card ${event.id==='d1-takahiro-join'?'highlight-event':''}`}><div className="event-top"><span className="event-time">{event.timeLabel}</span><span className="status-badge" data-status={event.status}>{statusLabel[event.status]}</span></div><h3>{event.title}</h3><p>{event.summary}</p><div className="event-actions"><button aria-expanded={open} aria-controls={`${event.id}-details`} onClick={()=>setOpen(!open)}>{open?'詳細を閉じる':'詳細を見る'} <span aria-hidden="true">{open?'−':'＋'}</span></button><MapLink spot={spot}/></div>{open&&<div id={`${event.id}-details`} className="event-details"><dl><div><dt>場所</dt><dd>{spot?.name??'調整中'}{spot?.address&&<span> · {spot.address}</span>}</dd></div><div><dt>参加予定</dt><dd>{event.participantIds.map(memberName).join('・')}</dd></div><div><dt>担当</dt><dd>{memberName(event.ownerId)}</dd></div><div><dt>予約</dt><dd>{reservation?<><strong>{reservationLabel[reservation.status]}</strong><br/>{reservation.publicNote}</>:'調整中'}</dd></div></dl>{event.details.length>0&&<ul>{event.details.map((detail,i)=><li key={i}>{detail}</li>)}</ul>}{event.travelNote&&<p>{event.travelNote}</p>}<External url={spot?.officialUrl} label="公式サイト"/></div>}</article></li>}
function Itinerary(){const {day}=useParams();if(day!=='day1'&&day!=='day2')return <NotFound/>;const dayId=day as DayId;const rows=dayEvents(dayId);return <><WoodTitle eyebrow="ADVENTURE ROUTE">{dayId==='day1'?'DAY 1':'DAY 2'}<small>{dayId==='day1'?'10月11日・日曜日':'10月12日・月曜日'}</small></WoodTitle><div className="page-intro"><p>{dayId==='day1'?'山と温泉へ。18:30にたかひろが合流予定。':'釣りとBBQ、最後まで6人で過ごす予定。'}</p><span>予定は変更になる場合があります。未確認は「調整中」と表示。</span></div><DaySwitcher active={dayId}/><div className={`route-scene route-scene-${dayId}`}><div className="route-header"><span>START</span><span>{dayId==='day1'?'合流前 5人 → 18:30以降 6人':'6人の予定'}</span></div><ol className="adventure-route">{rows.map((event,i)=><EventCard key={event.id} event={event} index={i}/>)}</ol></div><div className="route-end">✦　また次の冒険へ　✦</div></>}
function Members(){return <><h1 id="page-title" className="sr-only" tabIndex={-1}>仲間図鑑</h1><ImagePoster kind="members"/></>}
function Base(){const spot=spots[0];return <><WoodTitle eyebrow="BASE CAMP">旅の拠点</WoodTitle><div className="base-banner"><Icon name="base" size={44}/><div><span>2日間の拠点</span><h2>{spot.name}</h2><p>2026年10月11日 → 12日</p></div></div><section className="paper-panel"><h2>宿泊メモ</h2><dl className="info-list"><div><dt>チェックイン</dt><dd>{spot.checkInLabel} <small>調整中</small></dd></div><div><dt>チェックアウト</dt><dd>{spot.checkOutLabel??'調整中'}</dd></div><div><dt>住所</dt><dd>{spot.address??'調整中'}</dd></div><div><dt>宿泊プラン</dt><dd>調整中</dd></div></dl><div className="button-row"><MapLink spot={spot}/><External url={spot.officialUrl} label="公式サイト"/></div><ul className="simple-list">{spot.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></section><Link className="text-link" to="/info">食事やスポットの情報を見る →</Link></>}
function Info(){const sections:[string,string,Event[]][]=[['集合・交通','meeting',events.filter(e=>e.icon==='meeting'||e.id==='d2-departure')],['食事・買い出し','meal',events.filter(e=>['meal','shopping','sparkle'].includes(e.icon))],['観光・アクティビティ','mountain',events.filter(e=>['d1-park','d1-free','d2-fishing','d2-station'].includes(e.id))],['拠点・宿泊','hotel',events.filter(e=>['d1-checkin','d2-checkout'].includes(e.id))]];return <><WoodTitle eyebrow="TRAVEL NOTES">旅行情報</WoodTitle><p className="page-intro">旅程と同じ情報をまとめています。予約の成立や未確定時刻は確認でき次第更新します。</p><nav className="anchor-nav" aria-label="旅行情報の項目">{sections.map(([title,id])=><a key={id} href={`#${id}`}>{title}</a>)}</nav>{sections.map(([title,id,rows])=><section className="info-section" id={id} key={id}><h2>{title}</h2>{rows.map(e=>{const spot=spotById(e.spotId),res=reservationById(e.reservationId);return <article key={e.id} className="info-row"><div><span className="info-day">{e.dayId==='day1'?'DAY 1':'DAY 2'} · {e.timeLabel}</span><h3>{e.title}</h3><p>{e.summary}</p>{res&&<p className="reservation-note">{reservationLabel[res.status]} · {res.publicNote}</p>}</div><div className="info-row-links"><Link to={`/itinerary/${e.dayId}#${e.id}`}>旅程詳細 →</Link>{spot?.mapsUrl&&<External url={spot.mapsUrl} label="地図" kind="map"/>}</div></article>})}</section>)}<section className="paper-panel"><h2>確認しておきたいこと</h2><ul className="simple-list"><li>5人の集合場所・正式時刻と、たかひろの18:30集合場所</li><li>移動手段、帰路、雨天時の代替案</li><li>各施設の営業・利用条件、宿泊プラン</li><li>飲食店名と予約成立、釣り＆BBQの料金・人数</li></ul></section></>}
const packingKey='itsumen-yuzawa-2026:packing:v1';
function readPacking():{ids:Set<string>;warning:string|null}{try{const raw=localStorage.getItem(packingKey);if(!raw)return {ids:new Set(),warning:null};const parsed=JSON.parse(raw);if(parsed.schemaVersion!==1||!Array.isArray(parsed.checkedIds))throw Error('invalid');const known=new Set(packingItems.map(x=>x.id));return {ids:new Set(parsed.checkedIds.filter((id:unknown)=>typeof id==='string'&&known.has(id))),warning:null}}catch{return {ids:new Set(),warning:'保存済みのチェックを読み込めませんでした。空の状態で始めます。'}}}
function Packing(){const [initial]=useState(readPacking);const [checked,setChecked]=useState(initial.ids);const [warning,setWarning]=useState<string|null>(initial.warning);const [confirmClear,setConfirmClear]=useState(false);useEffect(()=>{const handle=()=>{const next=readPacking();setChecked(next.ids);setWarning(next.warning)};window.addEventListener('storage',handle);return()=>window.removeEventListener('storage',handle)},[]);function save(ids:Set<string>){setChecked(new Set(ids));try{localStorage.setItem(packingKey,JSON.stringify({schemaVersion:1,checkedIds:[...ids],updatedAt:new Date().toISOString()}));setWarning(null)}catch{setWarning('この端末に保存できません。閉じるとチェックが消える場合があります。')}}const groups=['必需品','衣類・身支度','あると便利'];return <><WoodTitle eyebrow="PACKING LIST">持ち物</WoodTitle><p className="page-intro">旅行準備の提案リストです。必要なものを確認してください。</p><div className="packing-progress"><div><strong>{checked.size}<small> / {packingItems.length}</small></strong><span>チェック済み</span></div><div className="progress-track"><span style={{width:`${checked.size/packingItems.length*100}%`}}/></div></div>{warning&&<p className="save-warning" role="status">{warning}</p>}{groups.map(group=><section className="packing-group" key={group}><h2>{group}</h2>{packingItems.filter(i=>i.category===group).map(item=><label className="packing-row" key={item.id}><input type="checkbox" checked={checked.has(item.id)} onChange={()=>{const next=new Set(checked);next.has(item.id)?next.delete(item.id):next.add(item.id);save(next)}}/><span className="fake-checkbox"><Icon name="check" size={17}/></span><span><strong>{item.label}</strong>{item.note&&<small>{item.note}</small>}</span></label>)}</section>)}{checked.size>0&&(confirmClear?<div className="clear-confirm"><p>すべてのチェックを解除しますか？</p><button onClick={()=>{save(new Set());setConfirmClear(false)}}>解除する</button><button onClick={()=>setConfirmClear(false)}>やめる</button></div>:<button className="clear-button" onClick={()=>setConfirmClear(true)}>チェックをすべて解除</button>)}<p className="storage-note">チェックはこの端末のブラウザに保存されます。ブラウザのデータを削除すると消えます。</p></>}
function NotFound(){return <><WoodTitle eyebrow="LOST IN THE WOODS">ページが見つかりません</WoodTitle><p className="page-intro">URLを確認してください。</p><Link className="solid-button" to="/">HOMEへ戻る <Icon name="arrow"/></Link></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><Layout/></BrowserRouter></React.StrictMode>);
